name: project_management_app
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '3.5.2'


#----------------- PACKAGES -----------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.1.0
  intl: ^0.18.1
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  otp_timer_button: ^1.1.1
  flutter_otp_text_field: ^1.1.3+2
  zoom_tap_animation: ^1.1.0
  contained_tab_bar_view: ^0.8.0
  iconly: ^1.0.1
  font_awesome_flutter: ^10.7.0
  easy_stepper: ^0.8.4
  flutter_switch: ^0.3.2
  flutter_advanced_switch: ^3.1.0
  banner_carousel: ^1.2.1
  flutter_easy_faq: ^1.0.1
  givestarreviews: ^1.0.2
  simple_animation_progress_bar: ^1.6.0
  dotted_border: ^2.1.0
  roundcheckbox: ^2.0.5
  url_launcher: ^6.3.0
  onboarding_animation: ^0.0.3
  lottie: any
  badges: ^3.1.2

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1
  expandable: ^5.0.1

  # Product Specific



  #------------------- ./ PACKAGES END ---------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/images/
    - assets/svgs/
    - assets/
    - assets/animations/

  # ------------------- LOCAL FONTS -----------------#
  fonts:
    - family: Outfit
      fonts:
        - asset: assets\fonts\outfit\Outfit-Light.ttf
          weight: 300
        - asset: assets\fonts\outfit\Outfit-Regular.ttf
          weight: 400
        - asset: assets\fonts\outfit\Outfit-Medium.ttf
          weight: 500
        - asset: assets\fonts\outfit\Outfit-SemiBold.ttf
          weight: 600
        - asset: assets\fonts\outfit\Outfit-Bold.ttf
          weight: 800
    - family: Montserrat
      fonts:
        - asset: assets\fonts\montserrat\Montserrat-Light.ttf
          weight: 300
        - asset: assets\fonts\montserrat\Montserrat-Regular.ttf
          weight: 400
        - asset: assets\fonts\montserrat\Montserrat-Italic.ttf
          style: italic
        - asset: assets\fonts\montserrat\Montserrat-Medium.ttf
          weight: 500
        - asset: assets\fonts\montserrat\Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets\fonts\montserrat\Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets\fonts\montserrat\Montserrat-Bold.ttf
          weight: 800
